name: Tests CI
on:   [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SESSION_SECRET: "834a4149-0edd-4d6e-a1e4-453492c7482b"
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/pokedex-tracker_e2e
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: pokedex-tracker_e2e
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16.18'

      - name: Install modules
        run: yarn install

      - name: Run Jest tests
        working-directory: server
        run: yarn run test
      
      - name: Migrate e2e database
        working-directory: server
        run: NODE_ENV=e2e yarn run db:e2e:migrate

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: yarn run dev:cypress
          wait-on: "http://127.0.0.1:8765"
          command: yarn run e2e:run
